// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEX35fpUpgVHPrx4wAb2pJkmsPWDPUwo',
    appId: '1:718681759794:web:2e6d65f15f6dc682ad1c2b',
    messagingSenderId: '718681759794',
    projectId: 'operationtreadstone-24753',
    authDomain: 'operationtreadstone-24753.firebaseapp.com',
    storageBucket: 'operationtreadstone-24753.appspot.com',
    measurementId: 'G-V7C7PJ9S7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa1WzEzUDK3JomhsAFP2uXxNMTTkLYAGM',
    appId: '1:718681759794:android:bf4e1681060959cdad1c2b',
    messagingSenderId: '718681759794',
    projectId: 'operationtreadstone-24753',
    storageBucket: 'operationtreadstone-24753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvg71P0BFF6efO_5FZ3eeu3QQbio-oZKY',
    appId: '1:718681759794:ios:29531830f4ee98fcad1c2b',
    messagingSenderId: '718681759794',
    projectId: 'operationtreadstone-24753',
    storageBucket: 'operationtreadstone-24753.appspot.com',
    iosBundleId: 'com.example.mfntreadstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvg71P0BFF6efO_5FZ3eeu3QQbio-oZKY',
    appId: '1:718681759794:ios:29531830f4ee98fcad1c2b',
    messagingSenderId: '718681759794',
    projectId: 'operationtreadstone-24753',
    storageBucket: 'operationtreadstone-24753.appspot.com',
    iosBundleId: 'com.example.mfntreadstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWEX35fpUpgVHPrx4wAb2pJkmsPWDPUwo',
    appId: '1:718681759794:web:3d6e8201be597d5fad1c2b',
    messagingSenderId: '718681759794',
    projectId: 'operationtreadstone-24753',
    authDomain: 'operationtreadstone-24753.firebaseapp.com',
    storageBucket: 'operationtreadstone-24753.appspot.com',
    measurementId: 'G-TM3E828TL1',
  );
}
